### ISSUE TITLE
Produce complete PackageDescriptions

### ISSUE THREAD

**Issue by ocharles** [ocharles/dhall-to-cabal#1]
Step one is to produce a complete `PackageDescription` value from a Dhall expression. This is the unconditional version of a .cabal file. Currently the https://github.com/ocharles/dhall-to-cabal/blob/master/Distribution/Package/Dhall.hs#L65 `packageDescription` Dhall interpreter is total, but fills many things in with defaults. All of these defaults need to be replaced with a recursive-descent into the given Dhall expression. 

If you want to help, make small pull requests, or maybe mention here if you want to "claim" responsibility for a bunch of fields.

**Comment by gilligan** [comment]
correct source code link is now:  https://github.com/ocharles/dhall-to-cabal/blob/master/lib/Distribution/Package/Dhall.hs#L72

**Comment by ocharles** [comment]
Thanks! I'm currently working on version bounds.

**Comment by ocharles** [comment]
I'm going to close this now. We haven't *strictly* got there, but I believe all fields are now supported, and the problem is pushed down into making sure those fields accept all possible values. It will be easier from this point forward to work on improving support at individual fields.
