### ISSUE TITLE
Have a canonical type or embrace a more flexible encoding?

### ISSUE THREAD

**Issue by ocharles** [ocharles/dhall-to-cabal#12]
https://github.com/ocharles/dhall-to-cabal/commit/e1545612872807e6bcb74735e584c4970b324882 begins an exploration of giving up a canonical type for cabal files to produce a more lightweight syntax. That commit only begins the work, but one could imagine writing:

```dhall
    let empty-package = ./dhall/empty-package.dhall 

in  let licenses = constructors ./dhall/types/License 

in  let extensions = constructors ./dhall/types/Extension 

in  let gitHub-project = ./dhall/gitHubProject.dhall 

in    gitHub-project { owner = "ocharles", repo = "dhall-to-cabal" }
    ⫽ { executables =
          { dhall-to-cabal =
                ./dhall/defaults/Executable.dhall 
              ⫽ { build-dependencies =
                    { dhall-to-cabal = anyVersion
                    , optparse-applicative =
                        unionVersionRanges
                          (majorBoundVersion [ +0, +13, +2 ])
                          (majorBoundVersion [ +0, +14 ])
                    }
                , hs-source-dirs     = [ "exe" ]
                , main-is            = "Main.hs"
                , other-extensions   = [ extensions.NamedFieldPuns {=} ]
                }
          }
      , library     =
            ./dhall/defaults/Library.dhall 
          ⫽ { build-dependencies =
                { containers = majorBoundVersion [ +0, +5 ]
                , ..
                }
            , compiler-options   =
                  ./dhall/defaults/CompilerOptions 
                ⫽ { GHC =
                      { build-options = [ "-Wall", "-fno-warn-name-shadowing" ]
                      }
                  }
            , exposed-modules    = [ "Distribution.Package.Dhall" ]
            , hs-source-dirs     = [ "lib" ]
            , other-extensions   =
                [ extensions.ApplicativeDo {=}
                , extensions.GADTs {=}
                , extensions.GeneralizedNewtypeDeriving {=}
                , extensions.LambdaCase {=}
                , extensions.OverloadedStrings {=}
                , extensions.RecordWildCards {=}
                , extensions.TypeApplications {=}
                ]
            , other-modules      = [ "Dhall.Extra" ]
            }
      , license     = licenses.MIT {=}
      , package     = { name = "dhall-to-cabal", version = [ +0, +1, +0 ] }
      }
```

Here both the top-level record has no canonical type, but nor do `build-dependencies`.

CC @Gabriel439

**Comment by Gabriel439** [comment]
To illustrate what I mean with a contrived example, if the executables are stored as a list instead of a record then I can do:

```
let generate = http://prelude.dhall-lang.org/List/generate
in
{ ...

  executables = generate +100 Executable makeExecutable
}
```

... which I can't do with a record.  I'd have to manually specify 100 fields.

Also, it's still not clear what syntax savings you are aiming for.  Could you provide a concise before-and-after of the relevant configuration options you want to shorten?

**Comment by ocharles** [comment]
Ok, https://github.com/ocharles/dhall-to-cabal/commit/ed4ac5db26848a52828cf233dfdbbf242833dff8 is a bit more compact.

**Comment by ocharles** [comment]
It's unclear what the final "prelude" will be, but at least this approach probably keeps building such a prelude to be something we can actually do. I'm convinced, I'll close this experiment for now and keep things how they are.

**Comment by Gabriel439** [comment]
Note that the next issue you will run into once you start providing a Prelude is how to distribute it.  You can always do something similar to what the Dhall Prelude does by using IPFS, as documented here:

* https://github.com/dhall-lang/dhall-haskell/tree/master/ipfs

... and then providing a convenient domain that redirects to the latest version on IPFS (i.e. like `http://prelude.dhall-lang.org`)

**Comment by ocharles** [comment]
I was actually planning on distributing via GitHub and tags, but I haven't
given that much thought yet.

**Comment by Gabriel439** [comment]
Oh yeah, I forgot that works, too.  That's waaaay simpler :)
