### ISSUE TITLE
Use code formatter

### ISSUE THREAD

**Issue by gilligan** [ocharles/dhall-to-cabal#8]
How about using some formatter? I am not sure about the formatting that you would like to using stylish-haskell or brittany would help me do PRs with the right syntax.

Any preferences ?

**Comment by ocharles** [comment]
Unfortunately there are no tools I know of that produces the format I'm currently writing. I may write something up, but I'm not actually too bothered about PRs having the correct formatting - I care more about functionality.

**Comment by gilligan** [comment]
> Unfortunately there are no tools I know of that produces the format I'm currently writing.

Fair enough, i think that is the very reason i was hoping I could have some tool do that for me haha.

Anyhow, lets just close this then.
